// Dutch A2 Vocabulary Dictionary
const vocabulary = {
    // Common verbs
    "huren": { en: "to rent", example: "Ik wil een garage huren. (I want to rent a garage.)" },
    "schrijven": { en: "to write", example: "Ik schrijf een e-mail. (I am writing an email.)" },
    "ophalen": { en: "to pick up", example: "Kun jij de kinderen ophalen? (Can you pick up the children?)" },
    "overwerken": { en: "to work overtime", example: "Ik moet vandaag overwerken. (I have to work overtime today.)" },
    "komen": { en: "to come", example: "Wanneer kan ik komen? (When can I come?)" },
    "ontvangen": { en: "to receive", example: "Ik heb de uitnodiging ontvangen. (I received the invitation.)" },
    "werken": { en: "to work", example: "Ik moet werken. (I have to work.)" },
    "hopen": { en: "to hope", example: "Ik hoop dat ik morgen beter ben. (I hope I'll be better tomorrow.)" },
    "helpen": { en: "to help", example: "Bedankt voor jullie hulp! (Thanks for your help!)" },
    "drinken": { en: "to drink", example: "Koffie drinken. (To drink coffee.)" },
    "kopen": { en: "to buy", example: "Ik heb een jas gekocht. (I bought a jacket.)" },
    "kosten": { en: "to cost", example: "De jas kostte 89 euro. (The jacket cost 89 euros.)" },
    "terugbrengen": { en: "to return/bring back", example: "Ik wil de jas terugbrengen. (I want to return the jacket.)" },
    "zwemmen": { en: "to swim", example: "Ik wil graag zwemmen. (I would like to swim.)" },
    "fitnessen": { en: "to do fitness", example: "Ik wil graag fitnessen. (I would like to do fitness.)" },
    "verliezen": { en: "to lose", example: "Ik ben mijn portemonnee verloren. (I lost my wallet.)" },
    "vinden": { en: "to find", example: "Heeft iemand hem gevonden? (Has anyone found it?)" },
    "inschrijven": { en: "to register/enroll", example: "Ik wil me inschrijven voor een cursus. (I want to register for a course.)" },
    "beginnen": { en: "to start/begin", example: "Ik wil in september beginnen. (I want to start in September.)" },
    "wachten": { en: "to wait", example: "Ik wacht op uw antwoord. (I am waiting for your answer.)" },
    "afzeggen": { en: "to cancel", example: "Ik moet de afspraak afzeggen. (I have to cancel the appointment.)" },
    "maken": { en: "to make", example: "Een afspraak maken. (To make an appointment.)" },
    "uitnodigen": { en: "to invite", example: "Ik wil je graag uitnodigen. (I would like to invite you.)" },
    "eten": { en: "to eat", example: "We gaan eten. (We are going to eat.)" },
    "meenemen": { en: "to bring along", example: "Je mag je man meenemen. (You may bring your husband.)" },

    // Common nouns
    "garage": { en: "garage", example: "Ik zoek een garage. (I'm looking for a garage.)" },
    "auto": { en: "car", example: "Ik heb een nieuwe auto. (I have a new car.)" },
    "huur": { en: "rent", example: "Wat is de huur per maand? (What is the rent per month?)" },
    "naam": { en: "name", example: "Mijn naam is... (My name is...)" },
    "adres": { en: "address", example: "Mijn adres is... (My address is...)" },
    "telefoonnummer": { en: "phone number", example: "Mijn telefoonnummer is... (My phone number is...)" },
    "kinderen": { en: "children", example: "De kinderen ophalen. (Pick up the children.)" },
    "school": { en: "school", example: "Van school ophalen. (Pick up from school.)" },
    "afspraak": { en: "appointment", example: "Een afspraak maken. (Make an appointment.)" },
    "dokter": { en: "doctor", example: "Ik ga naar de dokter. (I'm going to the doctor.)" },
    "koorts": { en: "fever", example: "Ik heb koorts. (I have a fever.)" },
    "hoofdpijn": { en: "headache", example: "Ik heb hoofdpijn. (I have a headache.)" },
    "uitnodiging": { en: "invitation", example: "Ik heb de uitnodiging ontvangen. (I received the invitation.)" },
    "ouderavond": { en: "parent evening", example: "De ouderavond op school. (The parent evening at school.)" },
    "mogelijkheid": { en: "possibility", example: "Is er een andere mogelijkheid? (Is there another possibility?)" },
    "werk": { en: "work/job", example: "Ik kan niet naar mijn werk komen. (I can't come to work.)" },
    "buren": { en: "neighbors", example: "Mijn buren zijn aardig. (My neighbors are nice.)" },
    "hulp": { en: "help", example: "Bedankt voor je hulp. (Thanks for your help.)" },
    "koffie": { en: "coffee", example: "Koffie drinken. (Drink coffee.)" },
    "winkel": { en: "store/shop", example: "In de winkel. (In the store.)" },
    "jas": { en: "jacket/coat", example: "Ik heb een jas gekocht. (I bought a jacket.)" },
    "mouw": { en: "sleeve", example: "Een gat in de mouw. (A hole in the sleeve.)" },
    "gat": { en: "hole", example: "Er zit een gat in. (There is a hole in it.)" },
    "geld": { en: "money", example: "Mijn geld terug. (My money back.)" },
    "bon": { en: "receipt", example: "Ik heb de bon nog. (I still have the receipt.)" },
    "sportschool": { en: "gym", example: "Bij de sportschool. (At the gym.)" },
    "abonnement": { en: "subscription/membership", example: "Een abonnement nemen. (Take out a subscription.)" },
    "informatie": { en: "information", example: "Meer informatie. (More information.)" },
    "openingstijden": { en: "opening hours", example: "Wat zijn de openingstijden? (What are the opening hours?)" },
    "zwembad": { en: "swimming pool", example: "Heeft u een zwembad? (Do you have a swimming pool?)" },
    "portemonnee": { en: "wallet", example: "Mijn portemonnee verloren. (Lost my wallet.)" },
    "bus": { en: "bus", example: "In de bus. (In the bus.)" },
    "lijn": { en: "line (bus/train)", example: "Lijn 12. (Line 12.)" },
    "identiteitskaart": { en: "ID card", example: "Mijn identiteitskaart. (My ID card.)" },
    "bankpas": { en: "bank card", example: "Mijn bankpas. (My bank card.)" },
    "cursus": { en: "course", example: "Een Nederlandse cursus. (A Dutch course.)" },
    "niveau": { en: "level", example: "Mijn niveau is A2. (My level is A2.)" },
    "les": { en: "lesson/class", example: "'s Avonds les. (Evening classes.)" },
    "boeken": { en: "books", example: "Zijn de boeken inbegrepen? (Are the books included?)" },
    "prijs": { en: "price", example: "Bij de prijs inbegrepen. (Included in the price.)" },
    "antwoord": { en: "answer", example: "Ik wacht op uw antwoord. (I'm waiting for your answer.)" },
    "ongemak": { en: "inconvenience", example: "Sorry voor het ongemak. (Sorry for the inconvenience.)" },
    "feestje": { en: "party", example: "Ik geef een feestje. (I'm having a party.)" },
    "taart": { en: "cake", example: "Er is taart. (There is cake.)" },
    "man": { en: "husband/man", example: "Je man. (Your husband.)" },

    // Time expressions
    "vandaag": { en: "today", example: "Ik moet vandaag overwerken. (I have to work overtime today.)" },
    "morgen": { en: "tomorrow", example: "Tot morgen! (See you tomorrow!)" },
    "gisteren": { en: "yesterday", example: "Gisteren heb ik... (Yesterday I...)" },
    "volgende week": { en: "next week", example: "Volgende week zaterdag. (Next week Saturday.)" },
    "vorige week": { en: "last week", example: "Vorige week dinsdag. (Last week Tuesday.)" },
    "'s avonds": { en: "in the evening", example: "'s Avonds les. (Evening classes.)" },
    "'s middags": { en: "in the afternoon", example: "'s Middags om twee uur. (In the afternoon at two o'clock.)" },

    // Days of the week
    "maandag": { en: "Monday", example: "Op maandag. (On Monday.)" },
    "dinsdag": { en: "Tuesday", example: "Op dinsdag. (On Tuesday.)" },
    "woensdag": { en: "Wednesday", example: "Op woensdag. (On Wednesday.)" },
    "donderdag": { en: "Thursday", example: "Op donderdag. (On Thursday.)" },
    "vrijdag": { en: "Friday", example: "Op vrijdag. (On Friday.)" },
    "zaterdag": { en: "Saturday", example: "Op zaterdag. (On Saturday.)" },
    "zondag": { en: "Sunday", example: "Op zondag. (On Sunday.)" },

    // Common adjectives
    "nieuw": { en: "new", example: "Een nieuwe auto. (A new car.)" },
    "groot": { en: "big/large", example: "Hoe groot is...? (How big is...?)" },
    "klein": { en: "small", example: "Een kleine portemonnee. (A small wallet.)" },
    "ziek": { en: "sick/ill", example: "Ik ben ziek. (I am sick.)" },
    "beter": { en: "better", example: "Ik ben weer beter. (I am better again.)" },
    "aardig": { en: "kind/nice", example: "Heel aardig van jullie. (Very kind of you.)" },
    "tevreden": { en: "satisfied", example: "Ik ben niet tevreden. (I am not satisfied.)" },
    "zwart": { en: "black", example: "Een zwarte portemonnee. (A black wallet.)" },
    "dringend": { en: "urgent", example: "Ik heb het dringend nodig. (I need it urgently.)" },
    "jarig": { en: "having a birthday", example: "Ik ben jarig. (It's my birthday.)" },

    // Common phrases
    "graag": { en: "gladly/please", example: "Ik wil graag... (I would like...)" },
    "helaas": { en: "unfortunately", example: "Helaas kan ik niet komen. (Unfortunately I cannot come.)" },
    "omdat": { en: "because", example: "Omdat ik moet werken. (Because I have to work.)" },
    "wanneer": { en: "when", example: "Wanneer kan ik komen? (When can I come?)" },
    "wat": { en: "what", example: "Wat kost het? (What does it cost?)" },
    "hoe": { en: "how", example: "Hoe groot is...? (How big is...?)" },
    "waar": { en: "where", example: "Waar is...? (Where is...?)" },
    "wie": { en: "who", example: "Wie is dat? (Who is that?)" },
    "per maand": { en: "per month", example: "50 euro per maand. (50 euros per month.)" },
    "direct": { en: "immediately/directly", example: "Direct beschikbaar. (Immediately available.)" },
    "beschikbaar": { en: "available", example: "Is het beschikbaar? (Is it available?)" },

    // Polite expressions
    "beste": { en: "dear (formal)", example: "Beste meneer/mevrouw. (Dear sir/madam.)" },
    "met vriendelijke groet": { en: "kind regards", example: "Met vriendelijke groet, [Naam]. (Kind regards, [Name].)" },
    "bedankt": { en: "thank you", example: "Bedankt voor je hulp. (Thank you for your help.)" },
    "sorry": { en: "sorry", example: "Sorry voor het ongemak. (Sorry for the inconvenience.)" },
    "alstublieft": { en: "please (formal)", example: "Kunt u alstublieft...? (Could you please...?)" },
    "kusjes": { en: "kisses (informal closing)", example: "Kusjes, Ellen. (Kisses, Ellen.)" },
    "groetjes": { en: "greetings (informal)", example: "Groetjes, [Naam]. (Greetings, [Name].)" },

    // Modal verbs
    "kunnen": { en: "can/to be able to", example: "Kun jij...? (Can you...?)" },
    "moeten": { en: "must/have to", example: "Ik moet werken. (I have to work.)" },
    "willen": { en: "to want", example: "Ik wil graag... (I would like...)" },
    "mogen": { en: "may/to be allowed", example: "Je mag meekomen. (You may come along.)" },

    // Prepositions
    "bij": { en: "at/with/near", example: "Bij de sportschool. (At the gym.)" },
    "in": { en: "in", example: "In de bus. (In the bus.)" },
    "op": { en: "on", example: "Op maandag. (On Monday.)" },
    "van": { en: "from/of", example: "Van school. (From school.)" },
    "voor": { en: "for", example: "Bedankt voor... (Thank you for...)" },
    "naar": { en: "to", example: "Naar de winkel. (To the store.)" },
    "om": { en: "at (time)", example: "Om tien uur. (At ten o'clock.)" },
    "tot": { en: "until", example: "Tot vijf uur. (Until five o'clock.)" },

    // Additional verbs from grammar exercises
    "lezen": { en: "to read", example: "Ik lees een boek. (I read a book.)" },
    "slapen": { en: "to sleep", example: "Zij slapen in bed. (They sleep in bed.)" },
    "spelen": { en: "to play", example: "Het kind speelt buiten. (The child plays outside.)" },
    "wonen": { en: "to live", example: "Wij wonen in Amsterdam. (We live in Amsterdam.)" },
    "leren": { en: "to learn/study", example: "Jullie leren Nederlands. (You learn Dutch.)" },
    "koken": { en: "to cook", example: "Wij koken eten. (We cook food.)" },
    "studeren": { en: "to study", example: "Mijn zoon studeert. (My son studies.)" },
    "liggen": { en: "to lie/be located", example: "Mijn bril ligt op tafel. (My glasses are on the table.)" },
    "huilen": { en: "to cry", example: "De baby huilt. (The baby cries.)" },
    "gaan": { en: "to go", example: "Ik ga naar school. (I go to school.)" },
    "zetten": { en: "to put/place", example: "Ik zet mijn schoen. (I put out my shoe.)" },
    "aantrekken": { en: "to put on (clothes)", example: "Een warme jas aantrekken. (Put on a warm coat.)" },
    "nemen": { en: "to take", example: "Zij neemt een paracetamol. (She takes a paracetamol.)" },
    "innemen": { en: "to take (medicine)", example: "Een paracetamol innemen. (Take a paracetamol.)" },

    // Additional nouns
    "brood": { en: "bread", example: "Jij eet brood. (You eat bread.)" },
    "boek": { en: "book", example: "Zij leest een boek. (She reads a book.)" },
    "bed": { en: "bed", example: "Zij slapen in bed. (They sleep in bed.)" },
    "kind": { en: "child", example: "Het kind speelt. (The child plays.)" },
    "zoon": { en: "son", example: "Mijn zoon studeert. (My son studies.)" },
    "baby": { en: "baby", example: "De baby huilt. (The baby cries.)" },
    "buren": { en: "neighbors", example: "Onze buren zijn aardig. (Our neighbors are nice.)" },
    "bomen": { en: "trees", example: "De bomen zijn groot. (The trees are big.)" },
    "tuin": { en: "garden", example: "In mijn tuin. (In mijn garden.)" },
    "deur": { en: "door", example: "Voor de deur. (In front of the door.)" },
    "winkels": { en: "stores/shops", example: "De winkels zijn open. (The stores are open.)" },
    "winkelcentrum": { en: "shopping center", example: "In het winkelcentrum. (In the shopping center.)" },
    "bril": { en: "glasses", example: "Mijn bril ligt op tafel. (My glasses are on the table.)" },
    "tafel": { en: "table", example: "Op tafel. (On the table.)" },
    "paracetamol": { en: "paracetamol/pain reliever", example: "Een paracetamol innemen. (Take a paracetamol.)" },
    "schoen": { en: "shoe", example: "Mijn schoen zetten. (Put out my shoe.)" },
    "moeder": { en: "mother", example: "Mijn moeder. (My mother.)" },
    "vader": { en: "father", example: "Mijn vader. (My father.)" },
    "jongen": { en: "boy", example: "De jongen speelt. (The boy plays.)" },
    "docent": { en: "teacher", example: "De docent. (The teacher.)" },
    "huiswerk": { en: "homework", example: "Het huiswerk maken. (Do the homework.)" },
    "toets": { en: "test", example: "De toets nakijken. (Grade the test.)" },
    "koning": { en: "king", example: "Koning Willem Alexander. (King Willem Alexander.)" },
    "park": { en: "park", example: "Naar het park gaan. (Go to the park.)" },
    "weer": { en: "weather", example: "Het is mooi weer. (The weather is nice.)" },

    // Conjunctions and connectors
    "want": { en: "because (main clause)", example: "Ik blijf thuis, want ik ben ziek. (I stay home because I am sick.)" },
    "en": { en: "and", example: "Ik koop appels en sinaasappels. (I buy apples and oranges.)" },
    "maar": { en: "but", example: "Het is duur, maar wel vers. (It's expensive, but fresh.)" },
    "dus": { en: "so/therefore", example: "Ik ben moe, dus ik ga slapen. (I'm tired, so I'm going to sleep.)" },
    "als": { en: "if/when", example: "Als het regent... (If/when it rains...)" },

    // Additional adjectives
    "open": { en: "open", example: "De winkels zijn open. (The stores are open.)" },
    "buiten": { en: "outside", example: "Het kind speelt buiten. (The child plays outside.)" },
    "warm": { en: "warm", example: "Een warme jas. (A warm coat.)" },
    "koud": { en: "cold", example: "Het is koud. (It is cold.)" },
    "mooi": { en: "beautiful/nice", example: "Mooi weer. (Nice weather.)" },
    "rood": { en: "red", example: "De auto is rood. (The car is red.)" },

    // Reading section vocabulary
    "vuurwerk": { en: "fireworks", example: "Vuurwerk afsteken. (Set off fireworks.)" },
    "afsteken": { en: "to set off/light", example: "Vuurwerk afsteken. (Set off fireworks.)" },
    "gemeente": { en: "municipality", example: "De gemeente Amsterdam. (The municipality of Amsterdam.)" },
    "folder": { en: "brochure/flyer", example: "Een folder met informatie. (A brochure with information.)" },
    "boete": { en: "fine", example: "Een boete van €100. (A fine of €100.)" },
    "verbod": { en: "ban/prohibition", example: "Een vuurwerkverbod. (A fireworks ban.)" },
    "kinderboerderij": { en: "petting zoo", example: "Bij de kinderboerderij. (At the petting zoo.)" },
    "jaarwisseling": { en: "New Year's Eve", example: "Tijdens de jaarwisseling. (During New Year's Eve.)" },
    "beschermen": { en: "to protect", example: "Je ogen beschermen. (Protect your eyes.)" },
    "ogen": { en: "eyes", example: "Mijn ogen. (My eyes.)" },
    "vriend": { en: "friend", example: "Mijn vriend. (My friend.)" },
    "kaaswinkel": { en: "cheese shop", example: "In de kaaswinkel. (In the cheese shop.)" },
    "trakteren": { en: "to treat", example: "Ik trakteer je. (I'll treat you.)" },
    "dagje uit": { en: "day out", example: "Een dagje uit. (A day out.)" },
    "bootje": { en: "small boat", example: "Een bootje huren. (Rent a small boat.)" },
    "water": { en: "water", example: "Het water op. (On the water.)" },
    "kerk": { en: "church", example: "Naar de kerk gaan. (Go to church.)" },
    "bezoek": { en: "visit", example: "Ik krijg bezoek. (I'm getting visitors.)" },
    "schade": { en: "damage", example: "Schade aan de auto. (Damage to the car.)" },
    "verzekering": { en: "insurance", example: "De verzekering betaalt. (The insurance pays.)" },
    "vergoeden": { en: "to reimburse/compensate", example: "De schade vergoeden. (Compensate the damage.)" },
    "schadevergoeding": { en: "compensation/damages", example: "Een schadevergoeding krijgen. (Receive compensation.)" },
    "polis": { en: "insurance policy", example: "In de polis staat... (The policy states...)" },
    "repareren": { en: "to repair", example: "De auto repareren. (Repair the car.)" },
    "eigen risico": { en: "deductible", example: "Een eigen risico van €250. (A deductible of €250.)" },
    "kilometers": { en: "kilometers", example: "Veel kilometers rijden. (Drive many kilometers.)" },
    "recht": { en: "right/entitlement", example: "U hebt recht op... (You are entitled to...)" },
    "basis": { en: "basis", example: "Op basis van... (Based on...)" },
    "meedelen": { en: "to inform/notify", example: "Wij kunnen u meedelen... (We can inform you...)" },

    // Additional common words
    "krant": { en: "newspaper", example: "In de krant. (In the newspaper.)" },
    "advertentie": { en: "advertisement", example: "Een advertentie zien. (See an advertisement.)" },
    "vragen": { en: "questions", example: "Drie vragen. (Three questions.)" },
    "vraag": { en: "question", example: "Een vraag stellen. (Ask a question.)" },
    "klaar": { en: "ready/finished", example: "Om drie uur klaar. (Finished at three o'clock.)" },
    "thuis": { en: "home/at home", example: "Ik ben thuis. (I am home.)" },
    "half": { en: "half", example: "Half zes. (Half past five / 5:30.)" },
    "kwart": { en: "quarter", example: "Kwart over drie. (Quarter past three / 3:15.)" },
    "uur": { en: "hour/o'clock", example: "Om vijf uur. (At five o'clock.)" },
    "blijven": { en: "to stay", example: "Ik moet blijven. (I have to stay.)" },
    "zeggen": { en: "to say/tell", example: "Zeg hoe laat... (Say what time...)" },
    "uitleggen": { en: "to explain", example: "Leg uit wat er aan de hand is. (Explain what's wrong.)" },
    "hand": { en: "hand", example: "Aan de hand. (Wrong/the matter.)" },
    "dagen": { en: "days", example: "Drie dagen. (Three days.)" },
    "al": { en: "already", example: "Ik ben al ziek. (I am already sick.)" }
};
